class Status:
    STATUS_CODE_DEFAULT = 0


class HttpResponseCode:
    HTTP_RESPONSE_SUCCESS = 200
    HTTP_RESPONSE_CREATED = 201
    HTTP_RESPONSE_SERVER_ERROR = 500


STATUS_HTTP_MAPPING = {
    Status.STATUS_CODE_DEFAULT: HttpResponseCode.HTTP_RESPONSE_SUCCESS,
}
